### ISSUE TITLE
Timeout Value on pingDUT() too high.

### ISSUE THREAD

**Issue by brokenpackets** [arista-eosext/PingCheck#1]
Timing pingDUT, it takes about 10 seconds to return when set for pingcount=2, ~5s timeout per ping. Do we want to limit this with -W for 1-2 seconds? Seeing fairly high timeouts currently that make it tough to hit the user-expected threshold, since it takes about 20 seconds to complete one cycle (with two hosts) + 10 second wait period + another 20 second cycle.

**Comment by archjeb** [comment]
Added a default of 2 seconds and can be configured with a range of 0-3600.
